/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "cmock.h"
#include "raptor/toggle_switch.h"
#include "gpio_callback_helper.h"
#include "Mockgpio.h"
#include "Mocktimer.h"

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_pin_goes_low(void);
extern void test_pin_goes_low_no_on_press_callback_defined(void);
extern void test_pin_goes_high(void);
extern void test_pin_goes_high_no_on_release_callback_defined(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
  Mockgpio_Init();
  Mocktimer_Init();
}
static void CMock_Verify(void)
{
  Mockgpio_Verify();
  Mocktimer_Verify();
}
static void CMock_Destroy(void)
{
  Mockgpio_Destroy();
  Mocktimer_Destroy();
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/test_toggle_switch.c");
  run_test(test_pin_goes_low, "test_pin_goes_low", 53);
  run_test(test_pin_goes_low_no_on_press_callback_defined, "test_pin_goes_low_no_on_press_callback_defined", 69);
  run_test(test_pin_goes_high, "test_pin_goes_high", 85);
  run_test(test_pin_goes_high_no_on_release_callback_defined, "test_pin_goes_high_no_on_release_callback_defined", 104);

  CMock_Guts_MemFreeFinal();
  return UNITY_END();
}
